version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    links:
      - db
      - mailhog
    depends_on:
      - db
      - mailhog
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USERNAME: ''
      SMTP_PASSWORD: ''

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: newsletter_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
    command: --default-authentication-plugin=mysql_native_password

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  db_data: